# Generated by Django 2.2.9 on 2020-02-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='commit_hash',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
